CC = gcc -Wall

	
exec1 : 
	$(CC) ex01/ex01.c 


exec2 : 
	$(CC) ex02/ex02.c 

exec3 : 
	$(CC) ex03/ex03.c 

exec4 : 
	$(CC) ex04/ex04.c 

run : 
	./a.out

clean :
	rm a.out

doc1 : 
	cp Doxyfile ex01;	doxygen ex01/ex01.c


doc2 : 
	cp Doxyfile ex02;	doxygen ex02/ex02.c


doc3 : 
	cp Doxyfile ex03;	doxygen ex03/ex03.c


doc4 : 
	cp Doxyfile ex04;	doxygen ex04/ex04.c
